### PR TITLE
Initialize tests

### PR DESCRIPTION
**Pull request by peter279k**
As title, initialize tests and integrate the Travis CI build service.

Please look at the latest [Travis CI build log](https://travis-ci.org/peter279k/Clickatell/builds/454484280).

### CODE REVIEW

**Comment by BenMorel** [comment]
Hi, thanks for the PR; I didn't add tests so far, because as it stands, they add very little value: you can only test that a method throws an exception when called with invalid data, but cannot test actual functionality.

I would either try to mock the Clickatell API in some way, or not include tests at all for now.

Also, I think that Clickatell have moved to a new API now, so this library might become obsolete, so maybe it's not worth it!

**Comment by peter279k** [comment]
Hi @BenMorel, thank you for your reply.

I think I just add the test with invalid data/credentials.

You're right. The actual API call functionality doesn't test well and it should use the `Mock` approach to complete that.

This PR is merged/closed I think it's up to you. You can add the `Mock` approach after merging this PR.

**Comment by BenMorel** [comment]
I won't merge it for now, as I said, I prefer to have no tests rather than tests that do not test the actual functionality!

Thanks for the effort though. I will review your PRs on the other repos as soon as I have time! 👍

**Comment by peter279k** [comment]
@BenMorel, thank you for your concern. I appreciate your help really.

**Pull request closed without merging**
